movie1project/movieshow/movieapp/urls.py
from . import views
from django . urls import path
app_name='movieapp'
urlpatterns=[
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movie1project/movieshow/movieshow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie1project/movieshow/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie1project/movieshow/movieapp/views.py
from django.shortcuts import render, redirect

from .form import MovieForm
from . models import Movie
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    return render(request,"index.html",{'movie_list':movie})
def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,"delete.html")

movie1project/movieshow/templates/add.html
{% extends 'base.html' %}
{% block body %}

<div class="border m-5">
    <form method="post" enctype="multipart/form-data" >



         {% csrf_token %}
         <h2>add movie</h2>
         <input type="text" name="name" placeholder="enter your movie name"><br>
         <input type="text" name="desc" placeholder="enter description"><br>
         <input type="text" name="year" placeholder="enter your movie year"><br>
         <input type="file" name="img"><br>
         <input type="submit">
    </form>
</div>
{% endblock %}

movie1project/movieshow/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index page</title>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    online movie app
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie1project/movieshow/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this movie?
    <input type="submit">
</form>

movie1project/movieshow/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-5">
            <h2>{{movie.name}}</h2>
            <h4>{{movie.desc}}</h4>
            <h5>{{movie.year}}</h5>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

movie1project/movieshow/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movie1project/movieshow/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class=" col-md-4 mb-8">
            <div class="destination-item position-relative overflow-hidden mb-2">
                <div class="card" style="width: 18rem;margin:40px 40px 40px 40px">
                    <img src="{{i.img.url}}" class="card-img-top" alt="..." height="250" >
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.desc}}</p>
                        <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">To know more</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}